#!/bin/sh
#
# Checks for JIRA issue numbers in the commit message before allowing the commit

egrep -ive '^\s*\#' "$1" | egrep -qi -e '^[^#]*\[\s*[A-Z0-9]+-[0-9]+\s*\]' "$1"

signal=$?
if [ ! $signal -eq 0 ]; then
  echo "\033[1;37m\033[41m! -> You forgot to add a reference to a JIRA Issue!\033[0m"
  exit $signal
fi
