#!/usr/bin/env ruby
#
# Checks for JIRA issue numbers in the commit message before allowing the commit

message = File.readlines(ARGV[0]).reject { |line| /\A\s*(#|\Z)/.match(line) }

exit 0 if message.empty?

unless message.detect{ |line| /\[\s*([A-Z0-9]+-[0-9]+|NO.?JIRA)\s*\]/.match(line) }
  puts "\033[1;37m\033[41m! -> You forgot to add a reference to a JIRA Issue!\033[0m"
  exit 0
end